const youtubedl = require("youtube-dl-exec");
const ffmpeg = require("fluent-ffmpeg");
const ffmpegPath = require("@ffmpeg-installer/ffmpeg").path;
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { EventEmitter } = require("events");
const debug = require("debug")("app:youtube");
const { TEMP_DIR, DOWNLOAD_DIR, sanitizeFilename } = require("../utils/helpers");
const poTokenService = require("./poTokenService");

const YTDLP_OPTS = {
  noCheckCertificates: true,
  noWarnings: true,
};

ffmpeg.setFfmpegPath(ffmpegPath);

// Ensure directories exist
for (const dir of [TEMP_DIR, DOWNLOAD_DIR]) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// Quality presets — each defines yt-dlp format + ffmpeg encoding settings
// Using 'bv' (best video) and 'ba' (best audio) as ultimate fallbacks
// to prevent "format not available" errors across different player clients
const QUALITY_PRESETS = {
  fast: {
    label: "Fast (480p)",
    description: "Lower quality, fastest download & encode",
    videoFormat: "bv[height<=480]/bv*[height<=480]/bv",
    preset: "ultrafast",
    crf: "28",
    audioBitrate: "128k",
  },
  balanced: {
    label: "Balanced (720p)",
    description: "Good quality, moderate speed",
    videoFormat: "bv[height<=720]/bv*[height<=720]/bv",
    preset: "fast",
    crf: "23",
    audioBitrate: "192k",
  },
  high: {
    label: "High (1080p)",
    description: "Best quality, takes longer",
    videoFormat: "bv[height<=1080]/bv*[height<=1080]/bv",
    preset: "medium",
    crf: "20",
    audioBitrate: "192k",
  },
  best: {
    label: "Best (Max Resolution)",
    description: "Maximum quality, slowest",
    videoFormat: "bv",
    preset: "medium",
    crf: "18",
    audioBitrate: "256k",
  },
};

/**
 * Build yt-dlp options with PO token and optional cookies.
 * This handles YouTube's bot detection by providing:
 * 1. PO Token + visitor_data via --extractor-args (primary)
 * 2. Cookies from user (fallback)
 */
async function buildAuthOpts(cookies) {
  const opts = { ...YTDLP_OPTS };

  // Try to get PO tokens (generated by headless browser)
  try {
    const { poToken, visitorData } = await poTokenService.getTokens();

    // Only force player-client=web when we have BOTH poToken and visitorData.
    // Without a valid PO token, restricting to web client causes format errors.
    if (poToken && visitorData) {
      const args = [
        `player-client=web`,
        `po_token=web+${poToken}`,
        `visitor_data=${visitorData}`,
      ];
      opts.extractorArgs = `youtube:${args.join(";")}`;
      debug("Using PO token with visitor_data for authentication");
    } else if (visitorData) {
      // Pass visitor_data without restricting player client
      opts.extractorArgs = `youtube:visitor_data=${visitorData}`;
      debug("Using visitor_data only (no PO token available)");
    }
  } catch (err) {
    debug("PO token retrieval failed: %s", err.message);
  }

  // If cookies are provided, write them to a temp file and pass to yt-dlp
  if (cookies) {
    const cookiePath = path.join(TEMP_DIR, `cookies_${crypto.randomBytes(4).toString("hex")}.txt`);
    fs.writeFileSync(cookiePath, cookies, "utf8");
    opts.cookies = cookiePath;
    opts._cookiePath = cookiePath; // Track for cleanup
    debug("Using user-provided cookies as fallback");
  }

  return opts;
}

/**
 * Clean up temporary cookie file if one was created.
 */
function cleanupCookieFile(opts) {
  if (opts._cookiePath && fs.existsSync(opts._cookiePath)) {
    fs.unlinkSync(opts._cookiePath);
  }
}

/**
 * Fetch video metadata from YouTube.
 */
async function getVideoInfo(url, cookies) {
  const authOpts = await buildAuthOpts(cookies);

  try {
    const info = await youtubedl(url, {
      dumpSingleJson: true,
      skipDownload: true,
      noCheckFormats: true,
      ...authOpts,
    });

    return {
      title: info.title,
      duration: info.duration || 0,
      channel: info.channel || info.uploader || "N/A",
      thumbnail: info.thumbnail,
    };
  } finally {
    cleanupCookieFile(authOpts);
  }
}

/**
 * Download video, download audio, merge into single .mp4, cleanup temp files.
 * Emits progress events on the returned emitter.
 * quality: one of "fast" | "balanced" | "high" | "best"
 */
function downloadAndMerge(url, quality = "balanced", cookies = null) {
  const progress = new EventEmitter();
  const preset = QUALITY_PRESETS[quality] || QUALITY_PRESETS.balanced;

  // Defer start to next tick so caller can attach event listeners first
  setImmediate(async () => {
    let authOpts = {};
    let jobDir = null;

    try {
      progress.emit("progress", { phase: "Preparing download...", percent: 0 });

      authOpts = await buildAuthOpts(cookies);
      progress.emit("progress", { phase: "Fetching video metadata...", percent: 2 });

      // Fetch just enough metadata for the filename
      const info = await youtubedl(url, {
        dumpSingleJson: true,
        skipDownload: true,
        noCheckFormats: true,
        ...authOpts,
      });

      const title = sanitizeFilename(info.title);
      const finalName = title + ".mp4";
      const finalPath = path.join(DOWNLOAD_DIR, finalName);
      const duration = info.duration || 0;

      const jobId = crypto.randomBytes(8).toString("hex");
      jobDir = path.join(TEMP_DIR, jobId);
      fs.mkdirSync(jobDir, { recursive: true });

      // Phase 1: Download video-only (5–35%)
      progress.emit("progress", { phase: "Downloading video", percent: 5 });
      const videoPath = path.join(jobDir, "video.mp4");
      await youtubedl(url, {
        output: videoPath,
        format: preset.videoFormat,
        ...authOpts,
      });
      progress.emit("progress", { phase: "Video downloaded", percent: 35 });

      // Phase 2: Download audio-only (35–55%)
      progress.emit("progress", { phase: "Downloading audio", percent: 35 });
      const audioPath = path.join(jobDir, "audio.m4a");
      await youtubedl(url, {
        output: audioPath,
        format: "ba[ext=m4a]/ba",
        ...authOpts,
      });
      progress.emit("progress", { phase: "Audio downloaded", percent: 55 });

      // Phase 3: Merge / re-encode with ffmpeg (55–100%)
      progress.emit("progress", { phase: "Encoding video", percent: 55 });
      await new Promise((resolve, reject) => {
        const cmd = ffmpeg()
          .input(videoPath)
          .input(audioPath)
          .outputOptions([
            "-c:v", "libx264",
            "-preset", preset.preset,
            "-crf", preset.crf,
            "-c:a", "aac",
            "-b:a", preset.audioBitrate,
            "-movflags", "+faststart",
            "-shortest",
          ])
          .output(finalPath);

        if (duration > 0) {
          cmd.on("progress", (p) => {
            const parts = (p.timemark || "0:0:0").split(":");
            const secs = (+parts[0]) * 3600 + (+parts[1]) * 60 + parseFloat(parts[2] || 0);
            const encodePercent = Math.min((secs / duration) * 100, 100);
            const overall = Math.round(55 + (encodePercent / 100) * 45);
            progress.emit("progress", { phase: "Encoding video", percent: overall });
          });
        }

        cmd
          .on("end", resolve)
          .on("error", reject)
          .run();
      });

      // Cleanup temp
      fs.rmSync(jobDir, { recursive: true, force: true });
      cleanupCookieFile(authOpts);

      const stats = fs.statSync(finalPath);
      progress.emit("progress", { phase: "Complete", percent: 100 });
      progress.emit("done", {
        title: info.title,
        filename: finalName,
        size: stats.size,
        filePath: finalPath,
      });
    } catch (err) {
      if (jobDir && fs.existsSync(jobDir)) {
        fs.rmSync(jobDir, { recursive: true, force: true });
      }
      cleanupCookieFile(authOpts);

      // If PO token failed, try refreshing tokens for next attempt
      if (err.message && err.message.includes("Sign in to confirm")) {
        debug("Bot detection triggered — refreshing PO tokens for next request");
        poTokenService.refreshTokens().catch(() => {});
      }

      progress.emit("error", err);
    }
  });

  return progress;
}

/**
 * Get the absolute path of a file in the downloads directory.
 * Returns null if invalid or not found.
 */
function getDownloadedFilePath(filename) {
  // Block path traversal: check for ../ or ..\ sequences, not just ".." anywhere
  if (filename.includes("../") || filename.includes("..\\") || filename.includes("/") || filename.includes("\\")) {
    return null;
  }
  const filePath = path.join(DOWNLOAD_DIR, filename);
  // Extra safety: ensure resolved path is still within DOWNLOAD_DIR
  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(DOWNLOAD_DIR))) {
    return null;
  }
  return fs.existsSync(resolved) ? resolved : null;
}

module.exports = {
  getVideoInfo,
  downloadAndMerge,
  getDownloadedFilePath,
  QUALITY_PRESETS,
};
